name: nestory

services:
  backend-builder:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    environment:
      - PORT=${BACKEND_CONTAINER_PORT}
    ports:
      - ${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO http://localhost:${BACKEND_CONTAINER_PORT}/healthz || exit 1",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
