name: nestory

services:
  backend-builder:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
  backend:
    image: nestory-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
      args:
        - APP_PORT=${BACKEND_CONTAINER_PORT}
    environment:
      - PORT=${BACKEND_CONTAINER_PORT}
    ports:
      - ${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}
