name: Build & Run Server

on:
  push:
  pull_request:

jobs:
  build:
    name: Build go executable & healthcheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create and Load .env
        run: |
          cp .env.example .env
          cat .env >> $GITHUB_ENV

      - name: Build the go executable
        run: make build-backend

      - name: Start backend container
        run: make run-backend

      - name: Test healthcheck endpoint
        run: |
          curl --fail --retry 5 --retry-connrefused --retry-delay 2 http://localhost:${BACKEND_HOST_PORT}/healthz

      - name: Stop containers
        if: always()
        run: make down
