name: Build

on:
  workflow_call:

jobs:
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Build backend Docker Image
        # Build the image and and compress it
        run: |
          docker build -t nestory-backend:latest ./backend
          docker save nestory-backend:latest | gzip > backend-image.tar.gz

      # Upload the compressed image artifact for upcoming jobs
      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: backend-docker-image
          path: backend-image.tar.gz
          retention-days: 1
