name: Build

on:
  workflow_call:

jobs:
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Build backend Docker Image
        # Build the image and and compress it
        run: |
          docker build -t nestory-backend:latest ./backend
          docker save nestory-backend:latest | gzip > backend-image.tar.gz

      # Upload the compressed image artifact for upcoming jobs
      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v7
        with:
          name: backend-docker-image
          path: backend-image.tar.gz
          retention-days: 1
