name: Healthcheck Test

on:
  workflow_call:

jobs:
  healthcheck:
    name: Backend Healthcheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Create and Load .env
        run: |
          cp .env.example .env
          cat .env >> $GITHUB_ENV

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3
        with:
          name: backend-docker-image

      - name: Unpack and load Docker Image
        run: |
          gunzip -c backend-image.tar.gz | docker load

      # Start backend container and --wait for native Dockerfile HEALTHCHECK
      - name: Start backend container & verify healthcheck
        run: docker compose up -d --wait backend

      # Show container logs if healthcheck fails
      - name: Print container logs on failure
        if: failure()
        run: docker compose logs backend

      - name: Stop containers
        if: always()
        run: docker compose down
