name: Nightly Vulnerability Audit

on:
  schedule:
    - cron: "0 2 * * *" # 02:00 AM UTC
  workflow_dispatch: # Allows manual run through GH Interface

jobs:
  lint-and-security:
    uses: ./.github/workflows/lint-security.yml

  build:
    needs: [lint-and-security]
    uses: ./.github/workflows/build.yml

  trivy-scan:
    needs: [build]
    uses: ./.github/workflows/trivy.yml
